//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme_Odevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public Nullable<int> BlogCategory { get; set; }
        public string Header { get; set; }
        public string Content_ { get; set; }
        public string BlogImg { get; set; }
    
        public virtual BlogCategories BlogCategories { get; set; }
    }
}
