//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme_Odevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindRecipe
    {
        public int Id { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<int> RecipeId { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Reicpes Reicpes { get; set; }
    }
}
