//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme_Odevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> MenuCategory { get; set; }
        public Nullable<int> Menu1Id { get; set; }
        public Nullable<int> Menu2Id { get; set; }
        public Nullable<int> Menu3Id { get; set; }
        public Nullable<int> Menu4Id { get; set; }
        public Nullable<int> Menu5Id { get; set; }
    
        public virtual MenuCategories MenuCategories { get; set; }
    }
}
