//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme_Odevi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekTarifleriEntities : DbContext
    {
        public YemekTarifleriEntities()
            : base("name=YemekTarifleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogCategories> BlogCategories { get; set; }
        public virtual DbSet<Ingredients> Ingredients { get; set; }
        public virtual DbSet<MenuCategories> MenuCategories { get; set; }
        public virtual DbSet<RecipeCategories> RecipeCategories { get; set; }
        public virtual DbSet<Reicpes> Reicpes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<FindRecipe> FindRecipe { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
    }
}
