//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme_Odevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reicpes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reicpes()
        {
            this.Comments = new HashSet<Comments>();
            this.FindRecipe = new HashSet<FindRecipe>();
        }
    
        public int Id { get; set; }
        public string RecipeName { get; set; }
        public Nullable<int> C_Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PrepTime { get; set; }
        public string CookTime { get; set; }
        public string Person { get; set; }
        public string Difficulty { get; set; }
        public Nullable<int> Calories { get; set; }
        public string RecipeImg { get; set; }
        public string Ingredienst { get; set; }
        public string RecipeDetails { get; set; }
    
        public virtual RecipeCategories RecipeCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindRecipe> FindRecipe { get; set; }
        public virtual Users Users { get; set; }
    }
}
